package Enums;

public enum Location {
			INTERIOR_FRONT, 
			INTERIOR_FRONT_DRIVERS,
			INTERIOR_FRONT_PASSANGERS,
			INTERIOR_REAR,
			INTERIOR_REAR_DRIVERS,
			INTERIOR_REAR_PASSANGERS,
			
			EXTERIOR_FRONT, 
			EXTERIOR_FRONT_DRIVERS,
			EXTERIOR_FRONT_PASSANGERS,
			EXTERIOR_REAR,
			EXTERIOR_REAR_DRIVERS,
			EXTERIOR_REAR_PASSANGERS,

			UNDERCARRIAGE_CENTER,
			UNDERCARRIAGE_FRONT, 
			UNDERCARRIAGE_FRONT_DRIVERS,
			UNDERCARRIAGE_FRONT_PASSANGERS,
			UNDERCARRIAGE_REAR,
			UNDERCARRIAGE_REAR_DRIVERS,
			UNDERCARRIAGE_REAR_PASSANGERS,
			
			ENGINE_BAY,
			ENGINE_BAY_TOP,
			ENGINE_BAY_BOTTOM,
			
			STORAGE,
			BFE,
			
			//Line locations
			TANK_TO_FILTER,
			FILTER_TO_PUMP,
			PUMP_TO_MOTOR,
			
			MASTER,
			MASTER_TO_FRONT_DRIVERS,
			MASTER_TO_FRONT_PASSANGERS,
			MASTER_TO_REAR_DRIVERS,
			MASTER_TO_REAR_PASSANGERS,
			
			//Wire locations
			BATTERY_TO_ALTERNATOR,
			BATTERY_TO_COMPUTER, 
			BATTERY_TO_STARTER, 
			BATTERY_TO_FUEL_PUMP,
			
			COMPUTER_TO_STARTER,
			COMPUTER_TO_MOTOR,
			COMPUTER_TO_IGNITION_SWITCH, 
			BATTERY_TO_IGNITION, 
			IGNITION_TO_COMPUTER, 
			IGNITION_TO_STARTER, 
			TANK_TO_MOTOR, 
			MOTOR,
			CAR, 
		
			;
	
			public Location addBrake(Location other){
				if(this == EXTERIOR_FRONT_DRIVERS && other == MASTER)
					return MASTER_TO_FRONT_DRIVERS;
				
				if(this == EXTERIOR_FRONT_PASSANGERS && other == MASTER)
					return MASTER_TO_FRONT_PASSANGERS;
				
				if(this == EXTERIOR_REAR_DRIVERS && other == MASTER)
					return MASTER_TO_FRONT_DRIVERS;
				
				if(this == EXTERIOR_REAR_PASSANGERS && other == MASTER)
					return MASTER_TO_FRONT_PASSANGERS;
				
				return BFE;
			}
}
